#!/usr/bin/env python3

from __future__ import annotations

import argparse
from pathlib import Path

from .generate_preprocessor_sql import (
    ARRAY_ITERATION_LUA,
    COMMON_LUA,
    DEFAULT_PREPROCESSOR_LIBRARY_SCRIPT,
    DISABLED_MODE_LUA,
    JOIN_MODE_LUA,
    MARKER_HELPER_REWRITE_LUA,
    ROOT,
    WRAPPER_EXPLICIT_NULL_HELPER_LUA,
    validate_identifier,
)


DEFAULT_OUTPUT = ROOT / "dist" / "exasol-json-tables" / "json_preprocessor_library.sql"
LIBRARY_TEMPLATE_PATH = Path(__file__).resolve().parent / "preprocessor_assets" / "jvs_preprocessor_lib.lua"


def _rename_local_function(block: str, original_name: str, renamed_name: str) -> str:
    original = f"local function {original_name}("
    replacement = f"local function {renamed_name}("
    if original not in block:
        raise ValueError(f"Could not find Lua function {original_name!r} in the shared preprocessor block.")
    return block.replace(original, replacement, 1)


def generate_preprocessor_library_body() -> str:
    template = LIBRARY_TEMPLATE_PATH.read_text()
    replacements = {
        "__COMMON_LUA__": COMMON_LUA.strip("\n"),
        "__ARRAY_ITERATION_LUA__": ARRAY_ITERATION_LUA.strip("\n"),
        "__JOIN_MODE_LUA__": _rename_local_function(
            JOIN_MODE_LUA.strip("\n"),
            "rewrite_path_identifiers_in_sql",
            "rewrite_path_identifiers_in_sql_join_mode",
        ),
        "__DISABLED_MODE_LUA__": _rename_local_function(
            DISABLED_MODE_LUA.strip("\n"),
            "rewrite_path_identifiers_in_sql",
            "rewrite_path_identifiers_in_sql_disabled",
        ),
        "__MARKER_HELPER_REWRITE_LUA__": MARKER_HELPER_REWRITE_LUA.strip("\n"),
        "__WRAPPER_HELPER_REWRITE_LUA__": _rename_local_function(
            WRAPPER_EXPLICIT_NULL_HELPER_LUA.strip("\n"),
            "rewrite_helper_calls_in_sql",
            "rewrite_helper_calls_in_sql_wrapper_mode",
        ),
    }
    for placeholder, value in replacements.items():
        template = template.replace(placeholder, value)
    return template.strip() + "\n"


def generate_preprocessor_library_sql_text(
    schema: str = "JVS_WRAP_PP",
    script: str = DEFAULT_PREPROCESSOR_LIBRARY_SCRIPT,
) -> str:
    validated_schema = validate_identifier("Schema", schema)
    validated_script = validate_identifier("Library script", script)
    body = generate_preprocessor_library_body()
    return f"""-- Generated by tools/generate_preprocessor_library_sql.py
-- Shared JSON Tables preprocessor runtime library. Generated wrappers import this script with exa.import(...).

CREATE SCHEMA IF NOT EXISTS {validated_schema};

CREATE OR REPLACE SCRIPT {validated_schema}.{validated_script} AS
{body}/
"""


def install_preprocessor_library(
    con,
    schema: str = "JVS_WRAP_PP",
    script: str = DEFAULT_PREPROCESSOR_LIBRARY_SCRIPT,
) -> tuple[str, str]:
    validated_schema = validate_identifier("Schema", schema)
    validated_script = validate_identifier("Library script", script)
    con.execute(f"CREATE SCHEMA IF NOT EXISTS {validated_schema}")
    con.execute(
        f"CREATE OR REPLACE SCRIPT {validated_schema}.{validated_script} AS\n"
        + generate_preprocessor_library_body()
        + "/"
    )
    return validated_schema, validated_script


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Generate installable Exasol SQL for the shared JSON Tables Lua preprocessor runtime library. "
            "Generated wrapper preprocessors import this library with exa.import(...)."
        )
    )
    parser.add_argument("--schema", default="JVS_WRAP_PP", help="Schema that will own the shared library script.")
    parser.add_argument(
        "--script",
        default=DEFAULT_PREPROCESSOR_LIBRARY_SCRIPT,
        help="Shared library script name.",
    )
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT, help="Output SQL file.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    sql_text = generate_preprocessor_library_sql_text(args.schema, args.script)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(sql_text)
    print(f"Wrote {args.output}")


if __name__ == "__main__":
    main()
