-- Generated by tools/generate_preprocessor_sql.py
-- Rewrites configured function calls to a CASE marker before virtual-schema optimization.
-- Configured function names: JSON_IS_EXPLICIT_NULL
-- Path identifier rewrite: disabled

CREATE SCHEMA IF NOT EXISTS JVS_PP;

CREATE OR REPLACE LUA PREPROCESSOR SCRIPT JVS_PP.JSON_NULL_PREPROCESSOR AS
    local TARGET_FUNCTIONS = {
        JSON_IS_EXPLICIT_NULL = true,
    }

    local function normalize(token)
        return sqlparsing.normalize(token)
    end

    local function is_ignored(token)
        return sqlparsing.iswhitespaceorcomment(token)
    end

    local CLAUSE_KEYWORDS = {
        WHERE = true, GROUP = true, ORDER = true, LIMIT = true, OFFSET = true,
        QUALIFY = true, CONNECT = true, START = true, UNION = true, MINUS = true,
        EXCEPT = true, HAVING = true
    }
    local QUERY_START_KEYWORDS = {
        SELECT = true, WITH = true, EXPLAIN = true
    }
    local EXPRESSION_START_KEYWORDS = {
        SELECT = true, WHERE = true, WHEN = true, THEN = true, ELSE = true,
        ON = true, AND = true, OR = true, NOT = true, BY = true, HAVING = true,
        QUALIFY = true, CONNECT = true, START = true, USING = true, IN = true,
        EXISTS = true, IS = true, CASE = true, BETWEEN = true, LIKE = true
    }
    local EXPRESSION_START_TOKENS = {
        [","] = true, ["("] = true, ["="] = true, [">"] = true, ["<"] = true,
        [">="] = true, ["<="] = true, ["<>"] = true, ["!="] = true, ["+"] = true,
        ["-"] = true, ["*"] = true, ["/"] = true, ["||"] = true
    }

    local function encode_quoted_identifier(identifier)
        return '"' .. string.gsub(identifier, '"', '""') .. '"'
    end

    local function encode_string_literal(value)
        return "'" .. string.gsub(value, "'", "''") .. "'"
    end

    local function decode_quoted_identifier(token)
        local out = {}
        local index = 2
        while index < #token do
            local ch = string.sub(token, index, index)
            if ch == '"' and string.sub(token, index + 1, index + 1) == '"' then
                out[#out + 1] = '"'
                index = index + 2
            else
                out[#out + 1] = ch
                index = index + 1
            end
        end
        return table.concat(out)
    end

    local function tokenize_path_sql(sqltext)
        local tokens = {}
        local index = 1
        while index <= #sqltext do
            local ch = string.sub(sqltext, index, index)
            local next_ch = string.sub(sqltext, index + 1, index + 1)
            if string.match(ch, "%s") then
                local start_index = index
                repeat
                    index = index + 1
                    ch = string.sub(sqltext, index, index)
                until index > #sqltext or not string.match(ch, "%s")
                tokens[#tokens + 1] = {type = "whitespace", text = string.sub(sqltext, start_index, index - 1)}
            elseif ch == "-" and next_ch == "-" then
                local start_index = index
                index = index + 2
                while index <= #sqltext and string.sub(sqltext, index, index) ~= "\n" do
                    index = index + 1
                end
                if index <= #sqltext then
                    index = index + 1
                end
                tokens[#tokens + 1] = {type = "comment", text = string.sub(sqltext, start_index, index - 1)}
            elseif ch == "/" and next_ch == "*" then
                local start_index = index
                index = index + 2
                while index <= #sqltext - 1 and string.sub(sqltext, index, index + 1) ~= "*/" do
                    index = index + 1
                end
                if index <= #sqltext - 1 then
                    index = index + 2
                end
                tokens[#tokens + 1] = {type = "comment", text = string.sub(sqltext, start_index, index - 1)}
            elseif ch == "'" then
                local start_index = index
                index = index + 1
                while index <= #sqltext do
                    local current = string.sub(sqltext, index, index)
                    if current == "'" then
                        if string.sub(sqltext, index + 1, index + 1) == "'" then
                            index = index + 2
                        else
                            index = index + 1
                            break
                        end
                    else
                        index = index + 1
                    end
                end
                tokens[#tokens + 1] = {type = "string", text = string.sub(sqltext, start_index, index - 1)}
            elseif ch == '"' then
                local start_index = index
                index = index + 1
                while index <= #sqltext do
                    local current = string.sub(sqltext, index, index)
                    if current == '"' then
                        if string.sub(sqltext, index + 1, index + 1) == '"' then
                            index = index + 2
                        else
                            index = index + 1
                            break
                        end
                    else
                        index = index + 1
                    end
                end
                local token_text = string.sub(sqltext, start_index, index - 1)
                tokens[#tokens + 1] = {
                    type = "quoted_identifier",
                    text = token_text,
                    identifier = decode_quoted_identifier(token_text)
                }
            elseif string.match(ch, "[A-Za-z_]") then
                local start_index = index
                index = index + 1
                while index <= #sqltext and string.match(string.sub(sqltext, index, index), "[A-Za-z0-9_]") do
                    index = index + 1
                end
                tokens[#tokens + 1] = {type = "word", text = string.sub(sqltext, start_index, index - 1)}
            elseif string.match(ch, "%d") then
                local start_index = index
                index = index + 1
                while index <= #sqltext and string.match(string.sub(sqltext, index, index), "[0-9]") do
                    index = index + 1
                end
                tokens[#tokens + 1] = {type = "number", text = string.sub(sqltext, start_index, index - 1)}
            else
                local two_chars = string.sub(sqltext, index, index + 1)
                if two_chars == ">=" or two_chars == "<=" or two_chars == "<>" or two_chars == "!="
                        or two_chars == "||" then
                    tokens[#tokens + 1] = {type = "punct", text = two_chars}
                    index = index + 2
                else
                    tokens[#tokens + 1] = {type = "punct", text = ch}
                    index = index + 1
                end
            end
        end
        return tokens
    end

    local function next_significant_path_token(tokens, index)
        local current = index
        while current <= #tokens and (tokens[current].type == "whitespace" or tokens[current].type == "comment") do
            current = current + 1
        end
        if current <= #tokens then
            return tokens[current], current
        end
        return nil, nil
    end

    local function previous_significant_path_token(tokens, index)
        local current = index
        while current >= 1 and (tokens[current].type == "whitespace" or tokens[current].type == "comment") do
            current = current - 1
        end
        if current >= 1 then
            return tokens[current], current
        end
        return nil, nil
    end

    local function normalize_path_token(token)
        if token == nil or token.type ~= "word" then
            return nil
        end
        return string.upper(token.text)
    end

    local function split_identifier_token(token)
        local parts = {}
        local current = {}
        local in_quotes = false
        local index = 1
        while index <= #token do
            local ch = string.sub(token, index, index)
            if ch == '"' then
                if in_quotes and string.sub(token, index + 1, index + 1) == '"' then
                    current[#current + 1] = '"'
                    index = index + 2
                else
                    in_quotes = not in_quotes
                    index = index + 1
                end
            elseif ch == "." and not in_quotes then
                parts[#parts + 1] = table.concat(current)
                current = {}
                index = index + 1
            else
                current[#current + 1] = ch
                index = index + 1
            end
        end
        parts[#parts + 1] = table.concat(current)
        return parts
    end

    local function parse_identifier_token(token)
        if token == nil then
            return nil
        end
        if string.sub(token, 1, 1) ~= '"' and not sqlparsing.isidentifier(token) then
            return nil
        end
        return split_identifier_token(token)
    end

    local function next_significant_raw(tokens, index)
        local current = index
        while current <= #tokens and is_ignored(tokens[current]) do
            current = current + 1
        end
        return current
    end

    local function previous_significant_raw(tokens, index)
        local current = index
        while current >= 1 and is_ignored(tokens[current]) do
            current = current - 1
        end
        return current
    end

    local function is_clause_keyword(token)
        local normalized = normalize(token)
        return normalized ~= nil and CLAUSE_KEYWORDS[normalized] == true
    end

    local function is_join_keyword(token)
        local normalized = normalize(token)
        return normalized == "JOIN" or normalized == "LEFT" or normalized == "RIGHT"
                or normalized == "FULL" or normalized == "INNER" or normalized == "CROSS"
    end

    local function is_path_query_statement(tokens)
        local first_token = next_significant_path_token(tokens, 1)
        if first_token == nil then
            return false
        end
        local normalized = normalize_path_token(first_token)
        return normalized ~= nil and QUERY_START_KEYWORDS[normalized] == true
    end

    local function can_start_expression_after_path_token(token)
        if token == nil then
            return false
        end
        if token.type == "punct" and EXPRESSION_START_TOKENS[token.text] == true then
            return true
        end
        local normalized = normalize_path_token(token)
        return normalized ~= nil and EXPRESSION_START_KEYWORDS[normalized] == true
    end

    local function is_clause_boundary_path_token(token)
        if token == nil then
            return true
        end
        if token.type == "punct" then
            return token.text == "," or token.text == ")"
        end
        local normalized = normalize_path_token(token)
        return normalized ~= nil and (CLAUSE_KEYWORDS[normalized] == true or normalized == "JOIN" or normalized == "LEFT"
                or normalized == "RIGHT" or normalized == "FULL" or normalized == "INNER"
                or normalized == "CROSS")
    end

    local function read_path_identifier(tokens, start_index)
        local token = tokens[start_index]
        if token == nil or token.type ~= "quoted_identifier" then
            return nil
        end

        local previous_token = previous_significant_path_token(tokens, start_index - 1)
        if previous_token ~= nil and (normalize_path_token(previous_token) == "AS"
                or (previous_token.type == "punct" and previous_token.text == ".")) then
            return nil
        end

        local next_token = next_significant_path_token(tokens, start_index + 1)
        if next_token ~= nil and next_token.type == "punct" and next_token.text == "." then
            return nil
        end

        if not can_start_expression_after_path_token(previous_token) and is_clause_boundary_path_token(next_token) then
            return nil
        end

        local identifier = token.identifier
        if string.find(identifier, "[", 1, true) or string.find(identifier, ".", 1, true) then
            return identifier
        end
        return nil
    end


    local function rewrite_path_identifiers_in_sql(sqltext)
        return sqltext
    end


    local function next_significant(tokens, index)
        local current = index
        while current <= #tokens and is_ignored(tokens[current]) do
            current = current + 1
        end
        return current
    end

    local function read_call(tokens, start_index)
        local identifier_index = next_significant(tokens, start_index)
        if identifier_index > #tokens then
            return nil
        end

        local current = identifier_index
        local identifier_parts = parse_identifier_token(tokens[current])
        if identifier_parts == nil then
            return nil
        end

        local last_identifier = normalize(identifier_parts[#identifier_parts])
        if last_identifier == nil then
            return nil
        end

        while true do
            local dot_index = next_significant(tokens, current + 1)
            if dot_index > #tokens or tokens[dot_index] ~= "." then
                break
            end
            local next_identifier = next_significant(tokens, dot_index + 1)
            if next_identifier > #tokens then
                return nil
            end
            current = next_identifier
            local next_identifier_parts = parse_identifier_token(tokens[current])
            if next_identifier_parts == nil then
                return nil
            end
            last_identifier = normalize(next_identifier_parts[#next_identifier_parts])
            if last_identifier == nil then
                return nil
            end
        end

        local opening_paren = next_significant(tokens, current + 1)
        if opening_paren > #tokens or tokens[opening_paren] ~= "(" then
            return nil
        end

        return {
            last_identifier = last_identifier,
            opening_paren = opening_paren
        }
    end

    local function find_matching_paren(tokens, opening_paren)
        local depth = 1
        local top_level_commas = 0
        local index = opening_paren + 1
        while index <= #tokens do
            if not is_ignored(tokens[index]) then
                if tokens[index] == "(" then
                    depth = depth + 1
                elseif tokens[index] == ")" then
                    depth = depth - 1
                    if depth == 0 then
                        return index, top_level_commas
                    end
                elseif tokens[index] == "," and depth == 1 then
                    top_level_commas = top_level_commas + 1
                end
            end
            index = index + 1
        end
        return nil, nil
    end

    local function rewrite(sqltext)
        local rewritten_sql = rewrite_path_identifiers_in_sql(sqltext)
        local tokens = sqlparsing.tokenize(rewritten_sql)
        local out = {}
        local index = 1
        while index <= #tokens do
            local call = read_call(tokens, index)
            if call and TARGET_FUNCTIONS[call.last_identifier] then
                local closing_paren, top_level_commas = find_matching_paren(tokens, call.opening_paren)
                if closing_paren ~= nil and top_level_commas == 0 then
                    out[#out + 1] = "(CASE WHEN "
                    for argument_index = call.opening_paren + 1, closing_paren - 1 do
                        out[#out + 1] = tokens[argument_index]
                    end
                    out[#out + 1] = " IS NULL THEN TRUE ELSE FALSE END)"
                    index = closing_paren + 1
                else
                    out[#out + 1] = tokens[index]
                    index = index + 1
                end
            else
                out[#out + 1] = tokens[index]
                index = index + 1
            end
        end
        return table.concat(out)
    end

    sqlparsing.setsqltext(rewrite(sqlparsing.getsqltext()))
/


-- Enable explicitly with:
-- ALTER SESSION SET SQL_PREPROCESSOR_SCRIPT = JVS_PP.JSON_NULL_PREPROCESSOR;

-- Example:
-- SELECT
--   CAST("id" AS VARCHAR(10)),
--   CASE WHEN JSON_IS_EXPLICIT_NULL("note") THEN '1' ELSE '0' END
-- FROM JSON_VS.SAMPLE
-- ORDER BY "id";
