#!/usr/bin/env python3

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
MRE_SRC = ROOT / "mre" / "udf-pushdown-stripping" / "src"
DIST = ROOT / "dist" / "udf_pushdown_mre_adapter.lua"


MODULES = [
    "MessageExpander",
    "ExaError",
    "remotelog",
    "exasol.vscl.text",
    "exasol.vscl.validator",
    "exasol.vscl.AdapterProperties",
    "exasol.vscl.AbstractVirtualSchemaAdapter",
    "exasol.vscl.Query",
    "exasol.vscl.queryrenderer.AbstractQueryAppender",
    "exasol.vscl.queryrenderer.ExpressionAppender",
    "exasol.vscl.queryrenderer.ScalarFunctionAppender",
    "exasol.vscl.queryrenderer.AggregateFunctionAppender",
    "exasol.vscl.queryrenderer.SelectAppender",
    "exasol.vscl.queryrenderer.ImportAppender",
    "exasol.vscl.ImportQueryBuilder",
    "exasol.vscl.QueryRenderer",
    "exasol.vscl.RequestDispatcher",
    "exasol.evscl.ExasolBaseAdapterProperties",
    "exasol.evscl.AbstractMetadataReader",
    "exasol.evscl.LocalMetadataReader",
    "exasol.evscl.AbstractQueryRewriter",
    "util.helpers",
    "mre_adapter.AdapterProperties",
    "mre_adapter.QueryRewriter",
    "mre_adapter.PassthroughAdapter",
]


def module_path(module_name: str) -> Path:
    source_root = MRE_SRC if module_name.startswith("mre_adapter.") else SRC
    if "." in module_name:
        return source_root / (module_name.replace(".", "/") + ".lua")
    return source_root / f"{module_name}.lua"


def emit_module(module_name: str, out_parts: list[str]) -> None:
    source = module_path(module_name).read_text()
    out_parts.append(f'__bundle["{module_name}"] = function()\n')
    out_parts.append(source)
    if not source.endswith("\n"):
        out_parts.append("\n")
    out_parts.append("end\n\n")


def main() -> None:
    out_parts = [
        "-- Generated by tools/bundle_udf_pushdown_mre.py\n\n",
        "local __native_require = require\n",
        "local __bundle = {}\n",
        "local __loaded = {}\n",
        "local function require(module_name)\n",
        "    local loader = __bundle[module_name]\n",
        "    if loader then\n",
        "        local loaded = __loaded[module_name]\n",
        "        if loaded ~= nil then\n",
        "            return loaded\n",
        "        end\n",
        "        local result = loader()\n",
        "        if result == nil then\n",
        "            result = true\n",
        "        end\n",
        "        __loaded[module_name] = result\n",
        "        return result\n",
        "    end\n",
        "    return __native_require(module_name)\n",
        "end\n\n",
    ]
    for module_name in MODULES:
        emit_module(module_name, out_parts)
    entry_source = (MRE_SRC / "entry.lua").read_text()
    out_parts.append(entry_source)
    if not entry_source.endswith("\n"):
        out_parts.append("\n")
    DIST.write_text("".join(out_parts))
    print(f"Wrote {DIST}")


if __name__ == "__main__":
    main()
